server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp15j8838mnpzwn9d0o.mysql.rds.aliyuncs.com/blog?
        useUnicode=true&characterEncoding=utf-8
    username: lhl253281
    password: 82515121zZ

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.lhl: info
  file: log/blog-pro.log
