server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp15j8838mnpzwn9d0o.mysql.rds.aliyuncs.com/blog?
      useUnicode=true&characterEncoding=utf-8
    username: lhl253281
    password: 82515121zZ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect



logging:
  level:
    root: info
    com.lhl: debug
  file: log/blog-dev.log
